In [67]:
import tensorflow as td
from tensorflow import keras
import numpy as np
data = keras.datasets.imdb
(train_data, train_labels), (test_data, test_labels)= data.load_data(num_words = 88000)


In [68]:
word_index = data.get_word_index()

In [69]:
# (train_date, train_labels), (test_data, test_labels)= data.load_data(num_words = 10000)

In [70]:
word_index = {k:(v+3) for k, v in word_index.items()}

In [71]:
word_index['<PAD>'] = 0
word_index['<START>'] = 1
word_index['<UNK>'] = 2
word_index['<UNUSED>'] = 3

In [72]:
reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])

In [73]:
train_data = keras.preprocessing.sequence.pad_sequences(train_data, value = word_index['<PAD>'], padding='post', maxlen=250)
test_data = keras.preprocessing.sequence.pad_sequences(test_data, value = word_index['<PAD>'], padding='post', maxlen=250)

In [74]:
def decode_review(text): 
    return " ".join([reverse_word_index.get(i, "?") for i in text])
print(decode_review(test_data[0]))

<START> please give this one a miss br br kristy swanson and the rest of the cast rendered terrible performances the show is flat flat flat br br i don't know how michael madison could have allowed this one on his plate he almost seemed to know this wasn't going to work out and his performance was quite lacklustre so all you madison fans give this a miss <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <

In [75]:
print(len(test_data[0]), len(test_data[1]))

250 250


In [76]:
model = keras.Sequential()
model.add(keras.layers.Embedding(88000, 16))
model.add(keras.layers.GlobalAveragePooling1D())
model.add(keras.layers.Dense(16, activation = 'relu'))
model.add(keras.layers.Dense(1, activation = 'sigmoid'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, None, 16)          1408000   
_________________________________________________________________
global_average_pooling1d_3 ( (None, 16)                0         
_________________________________________________________________
dense_6 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 17        
Total params: 1,408,289
Trainable params: 1,408,289
Non-trainable params: 0
_________________________________________________________________


In [77]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
x_val = train_data[:10000]
x_train = train_data[10000:]
y_val = train_labels[:10000]
y_train = train_labels[10000:]
fitModel = model.fit(x_train, y_train, epochs = 100, batch_size = 512, validation_data = (x_val, y_val), verbose = 1)

Train on 15000 samples, validate on 10000 samples
Epoch 1/100
15000/15000 [==============================] - 3s 219us/sample - loss: 0.6920 - accuracy: 0.5858 - val_loss: 0.6902 - val_accuracy: 0.6591
Epoch 2/100
15000/15000 [==============================] - 3s 174us/sample - loss: 0.6861 - accuracy: 0.7279 - val_loss: 0.6813 - val_accuracy: 0.7394
Epoch 3/100
15000/15000 [==============================] - 3s 169us/sample - loss: 0.6714 - accuracy: 0.7767 - val_loss: 0.6622 - val_accuracy: 0.7346
Epoch 4/100
15000/15000 [==============================] - 2s 158us/sample - loss: 0.6432 - accuracy: 0.7801 - val_loss: 0.6301 - val_accuracy: 0.7697
Epoch 5/100
15000/15000 [==============================] - 2s 155us/sample - loss: 0.6000 - accuracy: 0.8092 - val_loss: 0.5876 - val_accuracy: 0.7751
Epoch 6/100
15000/15000 [==============================] - 2s 157us/sample - loss: 0.5462 - accuracy: 0.8332 - val_loss: 0.5384 - val_accuracy: 0.8154
Epoch 7/100
15000/15000 [===================

15000/15000 [==============================] - 2s 159us/sample - loss: 0.0144 - accuracy: 0.9989 - val_loss: 0.3514 - val_accuracy: 0.8812
Epoch 55/100
15000/15000 [==============================] - 2s 164us/sample - loss: 0.0136 - accuracy: 0.9990 - val_loss: 0.3524 - val_accuracy: 0.8811
Epoch 56/100
15000/15000 [==============================] - 2s 157us/sample - loss: 0.0128 - accuracy: 0.9993 - val_loss: 0.3561 - val_accuracy: 0.8806
Epoch 57/100
15000/15000 [==============================] - 2s 152us/sample - loss: 0.0121 - accuracy: 0.9993 - val_loss: 0.3602 - val_accuracy: 0.8804
Epoch 58/100
15000/15000 [==============================] - 2s 151us/sample - loss: 0.0114 - accuracy: 0.9994 - val_loss: 0.3624 - val_accuracy: 0.8795
Epoch 59/100
15000/15000 [==============================] - 2s 158us/sample - loss: 0.0108 - accuracy: 0.9994 - val_loss: 0.3663 - val_accuracy: 0.8797
Epoch 60/100
15000/15000 [==============================] - 2s 159us/sample - loss: 0.0102 - accuracy

In [78]:
results = model.evaluate(test_data, test_labels)
print(results)

25000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.5327568479776382, 0.85932]


In [79]:
test_review = test_data[0]
predict = model.predict([test_review])
print("Review: ")
print(decode_review(test_review))
print("Prediction: " + str(predict[0]))
print("Actual: " + str(test_labels[0]))    
print(results)

Review: 
<START> please give this one a miss br br kristy swanson and the rest of the cast rendered terrible performances the show is flat flat flat br br i don't know how michael madison could have allowed this one on his plate he almost seemed to know this wasn't going to work out and his performance was quite lacklustre so all you madison fans give this a miss <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD> <PAD

In [80]:
model.save('model.h5')

In [96]:
def review_encode(s): 
    encoded = [1]
    for word in s: 
        if word in word_index: 
            encoded.append(word_index[word])
        else: 
            encoded.append(2)
        

In [83]:
model=keras.models.load_model('model.h5')

In [98]:
with open('test.txt', encoding = 'utf-8') as f: 
    for line in f.readlines(): 
        nline = line.replace(',', '').replace(',', '').replace('(', '').replace(')', '').replace(':', '').replace('\\','').strip().split(" ")
        encode = review_encode(nline)
        encode = keras.preprocessing.sequence.pad_sequences(train_data, value = word_index['<PAD>'], padding = 'post', maxlen = 250)
        predit= model.predict(encode)
        print(line)
        print(encode)
        print(predict[0])
                                                                                                                  

The service is average. Most of the information can be found on Google with a little diligence.

[[   1   14   22 ...    0    0    0]
 [   1  194 1153 ...    0    0    0]
 [   1   14   47 ...    0    0    0]
 ...
 [   1   11    6 ...    0    0    0]
 [   1 1446 7079 ...    0    0    0]
 [   1   17    6 ...    0    0    0]]
[0.]


[[   1   14   22 ...    0    0    0]
 [   1  194 1153 ...    0    0    0]
 [   1   14   47 ...    0    0    0]
 ...
 [   1   11    6 ...    0    0    0]
 [   1 1446 7079 ...    0    0    0]
 [   1   17    6 ...    0    0    0]]
[0.]
Watch your account, they will auto renew your account and not refund any of your money.
[[   1   14   22 ...    0    0    0]
 [   1  194 1153 ...    0    0    0]
 [   1   14   47 ...    0    0    0]
 ...
 [   1   11    6 ...    0    0    0]
 [   1 1446 7079 ...    0    0    0]
 [   1   17    6 ...    0    0    0]]
[0.]
